#!/bin/bash

dir="/projects_data"

mkdir 

cd 
mkdir prod
cd prod
mkdir data
mkdir couchdb
mkdir music
mkdir cover
mkdir cover_upload
chmod 777 cover_upload

cd 
mkdir test
cd prod
mkdir data
mkdir couchdb
mkdir music
mkdir cover
mkdir cover_upload
chmod 777 cover_upload

