#!/bin/bash

# update / upgrade
sudo apt-get update
sudo apt-get upgrade

# install prequisites
sudo apt-get -y install \
         apt-transport-https \
         ca-certificates \
         curl \
         gnupg2 \
         software-properties-common \
         python3-pip
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

# add repository
echo "deb [arch=armhf] https://download.docker.com/linux/debian \
         $(lsb_release -cs) stable" | \
         sudo tee /etc/apt/sources.list.d/docker.list
         
# install docker
curl -sSL https://get.docker.com | sh
#sudo apt-get -y install docker-ce
systemctl enable --now docker

# install docker-compose
sudo pip3 install docker-compose

# install mc
sudo apt-get -y install mc
