#!/bin/bash
# ---------------------------
# combine instructions for automatic wifi-hotspot from
# https://www.raspberryconnect.com/projects/65-raspberrypi-hotspot-accesspoints/158-raspberry-pi-auto-wifi-hotspot-switch-direct-connection

source config

test="" # add value to test the script
date=`date +%y%m%d`

echo
echo "Install Wifi Auto-hotspot ($date)"
echo "-------------------------------------"
echo "Source: https://www.raspberryconnect.com/" #projects/65-raspberrypi-hotspot-accesspoints/158-raspberry-pi-auto-wifi-hotspot-switch-direct-connection"
echo "Installation script by Christoph Kloth"
echo "-------------------------------------"
echo
if ! [ -f "config" ]; then
  echo "No config file available!"
  echo "Please copy sample file to 'config', edit and run this script again."
  exit 0
fi
echo "Press key - your options:"
echo " 'q' - exit"
echo " 't' - test"
echo " 'i' - install"
echo

count=0
while : ; do
   read -n 1 k <&1
   if [[ $k = q ]] ; then
       printf "\nQuitting from the program.\n"
       exit 0
   elif [[ $k = t ]] ; then
       printf "\nRunning in test mode ...\n"
       test=".test"
       break
   elif [[ $k = i ]] ; then
       printf "\nStart installation ...\n"
       break
   else
       ((count=$count+1))
       printf "\nIterate for $count times\n"
       echo "Press 'q' to exit"
   fi
done


if [[ $test = "" ]]; then
  # install software
  #-----------------------------
  sudo apt-get update
  sudo apt-get upgrade
  sudo apt-get install -y hostapd
  sudo apt-get install -y dnsmasq

  # disable automatic startup
  #-----------------------------
  sudo systemctl unmask hostapd
  sudo systemctl disable hostapd
  sudo systemctl disable dnsmasq
fi


# autohotspot
#-----------------------------
cp /etc/systemd/system/autohotspot.service /etc/systemd/system/autohotspot.service.backup$date
cat templates/autohotspot.service > /etc/systemd/system/autohotspot.service$test

cp /usr/bin/autohotspot /usr/bin/autohotspot.backup$date
cat templates/autohotspot > /usr/bin/autohotspot$test
sudo chmod +x /usr/bin/autohotspot$test


# dns: define ip range
#-----------------------------
cp /etc/dnsmasq.conf /etc/dnsmasq.conf.backup$date
cat templates/dnsmasq.conf > /etc/dnsmasq.conf$test


# hostapd
#-----------------------------
cp /etc/hostapd/hostapd.conf /etc/hostapd/hostapd.conf.backup$date
envsubst < "templates/hostapd.conf.template" > "/etc/hostapd/hostapd.conf$test"

file_name="/etc/default/hostapd"

file_content=$(cat $file_name)
file_content=$(echo "$file_content" | sed -e "s/#DAEMON_CONF\=\"\"/DAEMON_CONF\=\"\/etc\/hostapd\/hostapd.conf\"/g")
echo "$file_content"     > $file_name$test

file_content=$(cat $file_name$test)
file_content=$(echo "$file_content" | sed -e "s/DAEMON_OPTS\=/#DAEMON_OPTS\=/g")
echo "$file_content"     > $file_name$test


# dhcp: stop dhcpcd from starting the wifi network so the autohotspot script in the next step takes control of that
#-----------------------------
cp /etc/dhcpcd.conf /etc/dhcpcd.conf.backup$date
if [[ $test != "" ]]; then
  cp /etc/dhcpcd.conf /etc/dhcpcd.conf$test
fi
echo "" 			>> /etc/dhcpcd.conf$test
echo "nohook wpa_supplicant"	>> /etc/dhcpcd.conf$test


# interfaces: remove any entry from interfaces
#-----------------------------
cp /etc/network/interfaces /etc/network/interfaces.backup$date
cat templates/interfaces > /etc/network/interfaces$test


# wpa-supplicant
#-----------------------------
cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf.backup$date
envsubst < "templates/wpa_supplicant.conf.template" > "/etc/wpa_supplicant/wpa_supplicant.conf$test"


systemctl enable autohotspot.service

# instructions
#-----------------------------
echo
echo "Still to do manually ..."
echo
cat info.txt
echo
