#--------------------------------------------
# MBOX Client and Database
#----------------------------------------
# Please edit not here, but the orginial configuration file. This files is created using a template.
#----------------------------------------

version: "2"
services:

  mbox_client_prod:
    image: php:7.1-apache
    ports:
      - 85:5006
    volumes:
      - /projects/git/mbox/app:/var/www/html/app
      - ./config/apache2/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/apache2/www-app.conf:/etc/apache2/sites-enabled/www-app.conf

      - /projects_data/prod/data:/var/www/html/app/server/data
      - /projects_data/prod/music:/var/www/html/app/mbox_music
      - /projects_data/prod/cover:/var/www/html/app/cover
      - /projects_data/prod/cover_upload:/var/www/html/app/cover_upload

      - /projects/git/modules:/var/www/html/app/apps
 
#--------------------

  mbox_db_prod:
    image: apache/couchdb:latest
    ports:
      - 5105:5984
    volumes:
      - /projects_data/prod/couchdb:/opt/couchdb/data
    environment:
      - 'COUCHDB_USER=mbox'
      - 'COUCHDB_PASSWORD=mbox'

#----------------------------------------
