#!/bin/bash

#apt install apt-file
#apt-file update
#apt-file search "sdl-config"
#apt-get install libasound2
#apt-get install libasound2-dev
#apt-get install libsdl1.2-dev
#pip install pygame

pip3 install netaddr
pip3 install eyed3
pip3 install configparser
pip3 install flask
pip3 install flask-restful
pip3 install flask-httpauth
pip3 install flask-cors
pip3 install flask-restplus
pip3 install connexion[swagger-ui]
pip3 install python-vlc
pip3 install mutagen
pip3 install couchdb
pip3 install mpc
pip3 install watchdog


#apt-get install python3-dev python3-numpy
#apt-get install python-dev python-numpy
#sudo apt-get -y install alsa-base pulseaudio
