#!/bin/bash

dir="/projects_data"

mkdir $dir

cd $dir
mkdir prod
cd prod
mkdir data
mkdir couchdb
mkdir music
mkdir cover
mkdir cover_upload
chmod 777 cover_upload

cd $dir
mkdir test
cd prod
mkdir data
mkdir couchdb
mkdir music
mkdir cover
mkdir cover_upload
chmod 777 cover_upload

