#!/bin/bash
#--------------------------

config="config_$1"

echo
echo "-------------------------------------"
echo " Create jc://mbox/ configuration"
echo " (by Christoph Kloth)"
echo "-------------------------------------"

if [ ! $1 ]; then
  echo
  echo "Press key - your options:"
  echo " 'q' - exit"
  echo " 't' - test"
  echo " 'p' - prod"

  count=0
  while : ; do
    read -n 1 k <&1
    if [[ $k = q ]] ; then
       printf "\nQuitting from the program.\n"
       exit 0
    elif [[ $k = p ]] ; then
       config="$config""prod"
       printf "\nCreating prod ($config) ...\n"
       break
    elif [[ $k = t ]] ; then
       config="$config""test"
       printf "\nCreating test ($config) ...\n"
       break
    else
       ((count=$count+1))
       printf "\nIterate for $count times\n"
       echo "Press 'q' to exit"
    fi
  done
fi

if ! [ -f $config ]; then
  echo
  echo "ERROR: No config file available! Copy sample file to '$config', edit and run this script again."
  echo
  exit 0
fi

source $config

rm -rf ../docker-compose.yml
envsubst < "templates/docker-compose.yml" > "../docker-compose.yml"

rm -rf ../docker-compose-rpi.yml
envsubst < "templates/docker-compose-rpi.yml" > "../docker-compose-rpi.yml"

rm -rf ../app/config_stage.js
envsubst < "templates/config_stage.js" > "../app/config_stage.js"

rm -rf ../server/modules/config_stage.py
envsubst < "templates/config_stage.py" > "../server/modules/config_stage.py"

rm -rf install/install-datadir
envsubst < "templates/install-datadir" > "./install/install-datadir"
chmod 755 ./install/install-datadir

rm -rf install/install-rclocal
envsubst < "templates/install-rclocal" > "./install/install-rclocal"
chmod 755 ./install/install-rclocal

rm -rf $MBOX_DIR_DATA_ROOT/active.json
envsubst < "templates/active.json" > "$MBOX_DIR_DATA_ROOT/active.json"

echo
echo "Done."
echo
