#!/bin/bash
#--------------------------
# project specific substitution commands

echo ">> create files from templates for $MBOX_APP_VERSION ..."

# app-v1
if [[ $MBOX_APP_VERSION == "app-v1" ]]; then

  echo "> create docker & config (app-v1)"
  rm -rf ../$MBOX_APP_VERSION/config_stage.js
  envsubst < "templates/config_stage.js" > "../$MBOX_APP_VERSION/config_stage.js"

  rm -rf ../docker-compose.yml
  envsubst < "templates/docker-compose-v1.yml" > "../docker-compose.yml"

  rm -rf ../docker-compose-rpi.yml
  envsubst < "templates/docker-compose-rpi.yml" > "../docker-compose-rpi.yml"

  rm -rf ../server/modules/config_stage.py
  envsubst < "templates/config_stage.py" > "../server/modules/config_stage.py"

  rm -rf $MBOX_DIR_DATA_ROOT/active.json
  envsubst < "templates/active.json" > "$MBOX_DIR_DATA_ROOT/active.json"

  echo "> create start script (app-v1)"
  rm -rf ../start
  envsubst < "templates/start_mbox-v1" > "../start"
  chmod 755 ../start
fi

# app-v2
if [[ $MBOX_APP_VERSION == "app-v2" || $MBOX_APP_VERSION == "app" ]]; then

  echo "> create docker & config (app-v2)"
  rm -rf ../$MBOX_APP_VERSION/mbox_app/config_stage.js
  envsubst < "templates/config_stage.js" > "../$MBOX_APP_VERSION/mbox_app/config_stage.js"

  rm -rf ../docker-compose.yml
  envsubst < "templates/docker-compose-v2.yml" > "../docker-compose.yml"

  rm -rf ../docker-compose-rpi.yml
  envsubst < "templates/docker-compose-rpi.yml" > "../docker-compose-rpi.yml"

  rm -rf ../server/modules/config_stage.py
  envsubst < "templates/config_stage.py" > "../server/modules/config_stage.py"

  rm -rf $MBOX_DIR_DATA_ROOT/active.json
  envsubst < "templates/active.json" > "$MBOX_DIR_DATA_ROOT/active.json"

  echo "> create start script (app-v2)"
  rm -rf ../start
  envsubst < "templates/start_mbox-v2" > "../start"
  chmod 755 ../start
fi

# log dir
echo "> create log directory"
if [[ ! -d "../log" ]]; then
   mkdir ../log
fi

echo "> create installation scripts"
rm -rf install/install-datadir
envsubst < "templates/install-datadir" > "./install/install-datadir"
chmod 755 ./install/install-datadir

rm -rf install/install-rclocal
envsubst < "templates/install-rclocal" > "./install/install-rclocal"
chmod 755 ./install/install-rclocal

# autohotspot

echo "> create autohotspot"
if [[ $WIFI_PWD != "" ]] ; then
   rm -rf autohotspot/templates/autohotspot
   envsubst < "templates/autohotspot.template" > "autohotspot/templates/autohotspot"
   chmod 755 autohotspot/templates/autohotspot

   rm -rf autohotspot/templates/wpa_supplicant.conf
   envsubst < "templates/wpa_supplicant.conf.template" > "autohotspot/templates/wpa_supplicant.conf"

   wpa_passphrase $WIFI_SSID $WIFI_PWD >> autohotspot/templates/wpa_supplicant.conf

   rm -rf autohotspot/templates/hostapd.conf
   envsubst < "templates/hostapd.conf.template" > "autohotspot/templates/hostapd.conf"
else
   echo ">> No WIFI password defined. Skip autohotspot configuration."
fi

echo "< created"
