#!/bin/bash
#----------------------------------------
# ${THIS_IS_THE_PROJECT_TEMPLATE}
#----------------------------------------

echo "Clean up test data in directory '$MBOX_DIR/test_data/' ..."

cd $MBOX_DIR/test_data/couchdb
rm -r *

cd $MBOX_DIR/test_data/couchdb_backup
rm -r *

cd $MBOX_DIR/test_data/music
rm -r *

cd $MBOX_DIR/test_data/cover
rm -r *

cd $MBOX_DIR/test_data/cover_upload
rm -r *

cd $MBOX_DIR/test_data/test_music
cp -r * ../music/

rm /tmp/music-box-speech.mp3

echo "Done."
