#!/bin/bash
#----------------------------------------
# ${THIS_IS_THE_PROJECT_TEMPLATE}
#----------------------------------------

# ---> under construction
# del couch-db data
# clean music directory
# copy fresh music files to directory
