#!/bin/bash


dir="${MBOX_DIR}"
rclocal="/etc/rc.local"
rclocal_txt=$(cat ${DOLLAR}rclocal)

IFS='' read -r -d '' String <<"EOF"

# entries for jc://mbox/
#-----------------------------
#mount /dev/sda1 /media/usb/
#${MBOX_DIR_DOCKERCOMPOSE}/docker-compose -f ${MBOX_DIR}/docker-compose.yml up -d &
#${MBOX_DIR_DOCKERCOMPOSE}/docker-compose -f ${MBOX_DIR}/docker-compose-rpi.yml up -d &
${MBOX_DIR}/start_mbox docker &

exit 0
EOF

rclocal_txt=${DOLLAR}(echo "${DOLLAR}rclocal_txt" | sed -e "s/exit 0//g")
echo "${DOLLAR}rclocal_txt"     > ${DOLLAR}rclocal
echo "${DOLLAR}String"          >> ${DOLLAR}rclocal

