#!/bin/bash


dir="${MBOX_DIR}"
rclocal="/etc/rc.local"
rclocal_txt=$(cat ${DOLLAR}rclocal)

IFS='' read -r -d '' String <<"EOF"

# entries for jc://mbox/
#-----------------------------
${MBOX_DIR}/start_mbox docker &

exit 0
EOF

rclocal_txt=${DOLLAR}(echo "${DOLLAR}rclocal_txt" | sed -e "s/exit 0//g")
echo "${DOLLAR}rclocal_txt"     > ${DOLLAR}rclocal
echo "${DOLLAR}String"          >> ${DOLLAR}rclocal

