#!/bin/bash

dir="${MBOX_DIR_DATA_ROOT}"
usb_dev="${MBOX_MOUNT_USB}"
usb_mount="${MBOX_MOUNT_DATA}"

mkdir ${DOLLAR}dir

cd ${DOLLAR}dir
mkdir ${MBOX_CURRENT_STAGE}
cd ${MBOX_CURRENT_STAGE}
mkdir data
mkdir couchdb
mkdir cover
mkdir cover_upload
chmod 777 cover_upload

if [ ${DOLLAR}usb_dev == "" ]; then
   mkdir music
else
   mkdir -p ${DOLLAR}usb_dev
   ln -s ${DOLLAR}usb_dev music
fi
