#!/bin/bash


dir="${MBOX_DIR}"
rclocal="/etc/rc.local"
rclocal_txt=$(cat ${DOLLAR}rclocal)

IFS='' read -r -d '' String <<"EOF"

# entries for jc://mbox/
#-----------------------------
mount /dev/sda1 /media/usb/
/usr/local/bin/docker-compose -f ${MBOX_DIR}/docker-compose.yml up -d &
/usr/local/bin/docker-compose -f ${MBOX_DIR}/docker-compose-rpi.yml up -d &

exit 0
EOF

rclocal_txt=${DOLLAR}(echo "${DOLLAR}rclocal_txt" | sed -e "s/exit 0//g")
echo "${DOLLAR}rclocal_txt"     > ${DOLLAR}rclocal
echo "${DOLLAR}String"          >> ${DOLLAR}rclocal

